### ISSUE TITLE
about the code

### ISSUE THREAD

**Issue by amiltonwong** [liruihui/PointAugment#3]
Hi, @liruihui ,

Congratulations on your paper accepted to coming CVPR conference. When will the code be released?

THX!

**Comment by liruihui** [comment]
THX, I will prepare it once I back on campus.

**Comment by tchaton** [comment]
@amiltonwong @liruihui Currently integrating PointAugment in torch-points3d

Here is the current PR: https://github.com/nicolas-chaulet/torch-points3d/pull/264/files

**Comment by memoiry** [comment]
@liruihui 
Hi, is there any update?

**Comment by MaybeOjbk** [comment]
I still didn't find the code,can you give me the whole code?

**Comment by mzy97** [comment]
@tchaton the PR is duplicate and not merge into the main branch, in the PR page, only provide the model definition. Loss and training strategy is very important one, could you provide the full code in this repo, or where can i see the full code?
