### ISSUE TITLE
modelnet10_ply_hdf5_2048

### ISSUE THREAD

**Issue by upc-luxl** [liruihui/PointAugment#4]
Hello, could you provide a data set modelnet10_ply_hdf5_2048, thank you very much！

**Comment by liruihui** [comment]
You can find an vaid repository [POintDAN](https://github.com/canqin001/PointDAN)

**Comment by ardianumam** [comment]
Hi @liruihui : Thanks for the provided link :) So, does the ModelNet10 performance results in the PointAugment paper use the data you mentioned above ([POintDAN](https://github.com/canqin001/PointDAN))?
