### ISSUE TITLE
code for pointnet++, RS-CNN, and DGCNN

### ISSUE THREAD

**Issue by sheshap** [liruihui/PointAugment#7]
Dear Authors,

Thank you for sharing the code.
Can you please add the code for pointnet++, RS-CNN, and DGCNN?

**Comment by sheshap** [comment]
Please, also add pre-trained models

**Comment by liruihui** [comment]
> Dear Authors,
> 
> Thank you for sharing the code.
> Can you please add the code for pointnet++, RS-CNN, and DGCNN?

It can be easy to find them. There are also a lot of valid versions in GitHub.
[PointNet2](https://github.com/yanx27/Pointnet_Pointnet2_pytorch)
[DGCNN](https://github.com/WangYueFt/dgcnn/tree/master/pytorch)
[RSCNN](https://github.com/Yochengliu/Relation-Shape-CNN)
